### ISSUE TITLE
Possible Cooperation

### ISSUE THREAD

**Issue by SchulerSimon** [ambr0sial/fuckyoutube#1]
Hey, just a few days ago I created something similar: https://github.com/SchulerSimon/youfucktube Maybe we could cooperate on a project to bypass the adblock block. 

I'd love to improve accessibility. Maybe with a simple gui and standalone executable for major OS.

**Comment by ambr0sial** [comment]
hey! totally, you can add me on discord if you want to: waw#5437
a simple GUI would be awesome btw!

**Comment by SchulerSimon** [comment]
Ill get to it after work.
